import { Customer, CustomerType } from './types';

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust_1',
    type: CustomerType.PARENT,
    name: 'Global Corp Holdings',
    accountNumber: 'ACC-1001',
    isVip: true,
    addresses: [
      {
        id: 'addr_1',
        street: '123 Enterprise Blvd',
        city: 'Metropolis',
        state: 'NY',
        zipCode: '10101',
        isPrimary: true,
        isBilling: true,
        isGateProperty: false,
      }
    ],
    contacts: [
      {
        id: 'cont_1',
        name: 'Sarah Conner',
        email: 'sarah@globalcorp.com',
        phone: '555-0199',
        isPrimary: true,
      },
      {
        id: 'cont_2',
        name: 'Kyle Reese',
        email: 'kyle@globalcorp.com',
        phone: '555-0200',
        isPrimary: false,
      },
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cust_2',
    type: CustomerType.DIRECT,
    name: 'Tech Solutions Inc',
    accountNumber: 'ACC-2050',
    isVip: false,
    addresses: [
      {
        id: 'addr_2',
        street: '45 Silicon Valley Rd',
        city: 'Tech City',
        state: 'CA',
        zipCode: '94000',
        isPrimary: true,
        isBilling: true,
        isGateProperty: true,
      }
    ],
    parentId: 'cust_1',
    contacts: [
      {
        id: 'cont_3',
        name: 'John Doe',
        email: 'john@techsolutions.com',
        phone: '555-0300',
        isPrimary: true,
      },
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cust_3',
    type: CustomerType.DIRECT,
    name: 'Independent Coffee Roasters',
    accountNumber: 'ACC-3005',
    isVip: false,
    addresses: [
      {
        id: 'addr_3',
        street: '78 Bean St',
        city: 'Seattle',
        state: 'WA',
        zipCode: '98101',
        isPrimary: true,
        isBilling: true,
        isGateProperty: false,
      }
    ],
    parentId: null,
    contacts: [
      {
        id: 'cont_4',
        name: 'Jane Smith',
        email: 'jane@coffeeroasters.com',
        phone: '555-0400',
        isPrimary: true,
      },
    ],
    createdAt: new Date().toISOString(),
  },
  // --- Retail Group ---
  {
    id: 'cust_4',
    type: CustomerType.PARENT,
    name: 'National Retail Group',
    accountNumber: 'ACC-4000',
    isVip: true,
    addresses: [{ id: 'addr_4', street: '1 Market Plaza', city: 'Chicago', state: 'IL', zipCode: '60601', isPrimary: true, isBilling: true, isGateProperty: false }],
    contacts: [{ id: 'cont_5', name: 'Robert Retail', email: 'bob@nrg.com', phone: '555-1111', isPrimary: true }],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cust_5',
    type: CustomerType.DIRECT,
    name: 'NRG - North Outlet',
    accountNumber: 'ACC-4001',
    isVip: false,
    parentId: 'cust_4',
    addresses: [{ id: 'addr_5', street: '500 North Ave', city: 'Chicago', state: 'IL', zipCode: '60610', isPrimary: true, isBilling: true, isGateProperty: true }],
    contacts: [{ id: 'cont_6', name: 'Manager Mike', email: 'mike@nrg.com', phone: '555-1112', isPrimary: true }],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cust_6',
    type: CustomerType.DIRECT,
    name: 'NRG - South Outlet',
    accountNumber: 'ACC-4002',
    isVip: false,
    parentId: 'cust_4',
    addresses: [{ id: 'addr_6', street: '200 South Blvd', city: 'Chicago', state: 'IL', zipCode: '60616', isPrimary: true, isBilling: true, isGateProperty: true }],
    contacts: [{ id: 'cont_7', name: 'Manager Susan', email: 'susan@nrg.com', phone: '555-1113', isPrimary: true }],
    createdAt: new Date().toISOString(),
  },
  
  // --- Logistics Group ---
  {
    id: 'cust_7',
    type: CustomerType.PARENT,
    name: 'FastTrack Logistics',
    accountNumber: 'ACC-5000',
    isVip: false,
    addresses: [{ id: 'addr_7', street: '88 Cargo Way', city: 'Memphis', state: 'TN', zipCode: '38116', isPrimary: true, isBilling: true, isGateProperty: false }],
    contacts: [{ id: 'cont_8', name: 'Tom Hauler', email: 'tom@fasttrack.com', phone: '555-2222', isPrimary: true }],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cust_8',
    type: CustomerType.DIRECT,
    name: 'FastTrack Warehouse A',
    accountNumber: 'ACC-5001',
    isVip: false,
    parentId: 'cust_7',
    addresses: [{ id: 'addr_8', street: '89 Cargo Way', city: 'Memphis', state: 'TN', zipCode: '38116', isPrimary: true, isBilling: true, isGateProperty: true }],
    contacts: [{ id: 'cont_9', name: 'Foreman Fred', email: 'fred@fasttrack.com', phone: '555-2223', isPrimary: true }],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cust_9',
    type: CustomerType.DIRECT,
    name: 'FastTrack Warehouse B',
    accountNumber: 'ACC-5002',
    isVip: false,
    parentId: 'cust_7',
    addresses: [{ id: 'addr_9', street: '90 Cargo Way', city: 'Memphis', state: 'TN', zipCode: '38116', isPrimary: true, isBilling: true, isGateProperty: true }],
    contacts: [{ id: 'cont_10', name: 'Foreman George', email: 'george@fasttrack.com', phone: '555-2224', isPrimary: true }],
    createdAt: new Date().toISOString(),
  },

  // --- Independent Customers ---
  {
    id: 'cust_10',
    type: CustomerType.DIRECT,
    name: 'Mom & Pop Corner Store',
    accountNumber: 'ACC-6001',
    isVip: false,
    parentId: null,
    addresses: [{ id: 'addr_10', street: '12 Main St', city: 'Smallville', state: 'KS', zipCode: '66002', isPrimary: true, isBilling: true, isGateProperty: false }],
    contacts: [{ id: 'cont_11', name: 'Martha Kent', email: 'martha@smallville.com', phone: '555-3333', isPrimary: true }],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cust_11',
    type: CustomerType.DIRECT,
    name: 'Apex Constructions',
    accountNumber: 'ACC-6002',
    isVip: true,
    parentId: null,
    addresses: [{ id: 'addr_11', street: '500 Build It Dr', city: 'Austin', state: 'TX', zipCode: '73301', isPrimary: true, isBilling: true, isGateProperty: false }],
    contacts: [{ id: 'cont_12', name: 'Bob Builder', email: 'bob@apex.com', phone: '555-3334', isPrimary: true }],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cust_12',
    type: CustomerType.DIRECT,
    name: 'Green Thumb Landscaping',
    accountNumber: 'ACC-6003',
    isVip: false,
    parentId: null,
    addresses: [{ id: 'addr_12', street: '400 Garden Ln', city: 'Portland', state: 'OR', zipCode: '97201', isPrimary: true, isBilling: true, isGateProperty: false }],
    contacts: [{ id: 'cont_13', name: 'Ivy Plant', email: 'ivy@green.com', phone: '555-3335', isPrimary: true }],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cust_13',
    type: CustomerType.DIRECT,
    name: 'Digital Nomads Co-working',
    accountNumber: 'ACC-6004',
    isVip: false,
    parentId: null,
    addresses: [{ id: 'addr_13', street: '100 Wifi Blvd', city: 'San Francisco', state: 'CA', zipCode: '94105', isPrimary: true, isBilling: true, isGateProperty: false }],
    contacts: [{ id: 'cont_14', name: 'Tech Bro', email: 'admin@nomads.com', phone: '555-3336', isPrimary: true }],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cust_14',
    type: CustomerType.DIRECT,
    name: 'Oceanic Shipping',
    accountNumber: 'ACC-6005',
    isVip: true,
    parentId: null,
    addresses: [{ id: 'addr_14', street: '1 Harbor View', city: 'Miami', state: 'FL', zipCode: '33101', isPrimary: true, isBilling: true, isGateProperty: false }],
    contacts: [{ id: 'cont_15', name: 'Captain Jack', email: 'jack@oceanic.com', phone: '555-3337', isPrimary: true }],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cust_15',
    type: CustomerType.DIRECT,
    name: 'Mountain High Gear',
    accountNumber: 'ACC-6006',
    isVip: false,
    parentId: null,
    addresses: [{ id: 'addr_15', street: '500 Summit Dr', city: 'Denver', state: 'CO', zipCode: '80201', isPrimary: true, isBilling: true, isGateProperty: false }],
    contacts: [{ id: 'cont_16', name: 'Cliff Hanger', email: 'cliff@mountain.com', phone: '555-3338', isPrimary: true }],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cust_16',
    type: CustomerType.DIRECT,
    name: 'Urban Eats Delivery',
    accountNumber: 'ACC-6007',
    isVip: false,
    parentId: null,
    addresses: [{ id: 'addr_16', street: '50 Food Court', city: 'New York', state: 'NY', zipCode: '10001', isPrimary: true, isBilling: true, isGateProperty: false }],
    contacts: [{ id: 'cont_17', name: 'Del Ivery', email: 'del@urban.com', phone: '555-3339', isPrimary: true }],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cust_17',
    type: CustomerType.DIRECT,
    name: 'Solar Power Systems',
    accountNumber: 'ACC-6008',
    isVip: true,
    parentId: null,
    addresses: [{ id: 'addr_17', street: '99 Sun Ray Dr', city: 'Phoenix', state: 'AZ', zipCode: '85001', isPrimary: true, isBilling: true, isGateProperty: false }],
    contacts: [{ id: 'cont_18', name: 'Sunny Day', email: 'sunny@solar.com', phone: '555-3340', isPrimary: true }],
    createdAt: new Date().toISOString(),
  },
  
  // --- More Parent/Child for Pagination ---
  {
    id: 'cust_18',
    type: CustomerType.PARENT,
    name: 'HealthPlus Hospitals',
    accountNumber: 'ACC-7000',
    isVip: true,
    addresses: [{ id: 'addr_18', street: '1 Health Way', city: 'Boston', state: 'MA', zipCode: '02115', isPrimary: true, isBilling: true, isGateProperty: false }],
    contacts: [{ id: 'cont_19', name: 'Dr. House', email: 'house@healthplus.com', phone: '555-4444', isPrimary: true }],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cust_19',
    type: CustomerType.DIRECT,
    name: 'HealthPlus - Downtown Clinic',
    accountNumber: 'ACC-7001',
    isVip: false,
    parentId: 'cust_18',
    addresses: [{ id: 'addr_19', street: '20 Downtown St', city: 'Boston', state: 'MA', zipCode: '02110', isPrimary: true, isBilling: true, isGateProperty: true }],
    contacts: [{ id: 'cont_20', name: 'Nurse Joy', email: 'joy@healthplus.com', phone: '555-4445', isPrimary: true }],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cust_20',
    type: CustomerType.DIRECT,
    name: 'HealthPlus - ER Center',
    accountNumber: 'ACC-7002',
    isVip: false,
    parentId: 'cust_18',
    addresses: [{ id: 'addr_20', street: '22 Emergency Ln', city: 'Boston', state: 'MA', zipCode: '02111', isPrimary: true, isBilling: true, isGateProperty: true }],
    contacts: [{ id: 'cont_21', name: 'Dr. Strange', email: 'strange@healthplus.com', phone: '555-4446', isPrimary: true }],
    createdAt: new Date().toISOString(),
  },
   {
    id: 'cust_21',
    type: CustomerType.DIRECT,
    name: 'HealthPlus - Research Lab',
    accountNumber: 'ACC-7003',
    isVip: false,
    parentId: 'cust_18',
    addresses: [{ id: 'addr_21', street: '50 Science Park', city: 'Cambridge', state: 'MA', zipCode: '02139', isPrimary: true, isBilling: true, isGateProperty: true }],
    contacts: [{ id: 'cont_22', name: 'Scientist Sam', email: 'sam@healthplus.com', phone: '555-4447', isPrimary: true }],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cust_22',
    type: CustomerType.DIRECT,
    name: 'Alpha Omega Fraternity',
    accountNumber: 'ACC-8001',
    isVip: false,
    parentId: null,
    addresses: [{ id: 'addr_22', street: '1 Greek Row', city: 'College Town', state: 'OH', zipCode: '45056', isPrimary: true, isBilling: true, isGateProperty: false }],
    contacts: [{ id: 'cont_23', name: 'Chad Bro', email: 'chad@ao.com', phone: '555-5555', isPrimary: true }],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cust_23',
    type: CustomerType.DIRECT,
    name: 'Beta Gamma Sorority',
    accountNumber: 'ACC-8002',
    isVip: false,
    parentId: null,
    addresses: [{ id: 'addr_23', street: '2 Greek Row', city: 'College Town', state: 'OH', zipCode: '45056', isPrimary: true, isBilling: true, isGateProperty: false }],
    contacts: [{ id: 'cont_24', name: 'Stacy Sis', email: 'stacy@bg.com', phone: '555-5556', isPrimary: true }],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cust_24',
    type: CustomerType.DIRECT,
    name: 'City Library System',
    accountNumber: 'ACC-9000',
    isVip: false,
    parentId: null,
    addresses: [{ id: 'addr_24', street: '100 Book Rd', city: 'Reading', state: 'PA', zipCode: '19601', isPrimary: true, isBilling: true, isGateProperty: false }],
    contacts: [{ id: 'cont_25', name: 'Marian Librarian', email: 'marian@library.com', phone: '555-6666', isPrimary: true }],
    createdAt: new Date().toISOString(),
  }
];

export const EMPTY_CONTACT = {
  id: '',
  name: '',
  email: '',
  phone: '',
  isPrimary: false,
};